- hosts: all
  become: yes
  tasks:
    - name: Install Nginx web server
      shell: apt install nginx -y

    - name: Update index.html file
      copy:
        dest: "/var/www/html/index.nginx-debian.html"
        content: |
          <h1>Hello Ansible</h1>