pipeline {
    agent {
        docker {
            image 'nginx:latest' 
        }
    }
    stages {
        stage('Create a container') {
            steps {
                sh 'docker run -d --name test -p 90:80 nginx'
            }
        }
        
    }
}
