// pipeline {
//     agent {
//         docker {
//             image 'node:latest' 
//         }
//     }
//     stages {
//         stage('Create a container') {
//             steps {
//                 sh 'node --version'
//             }
//         }
        
//     }
// }



pipeline {
    agent {

    }
    stages {
        stage('Check git code') {
            steps {
                git 'https://github.com/awsdevops183/go-web-app.git'
            }
        }
         stage('Create Docker file') {
            steps {
             sh 'docker build -t awsdevosp183/go-web-app:v1'
             sh 'docker push awsdevosp183/go-web-app:v1'
            }
        }
        stage('Deploy resources on Kubernetes cluster') {
            steps {
             sh 'kubectl apply -f ./k8s/manifests/'
            }
        }
        
    }
}