pipeline {
    agent {
        docker {
            image 'node:latest' 
        }
    }
    stages {
        stage('Create a container') {
            steps {
                sh 'node --version'
            }
        }
        
    }
}
